name: CI Workflow

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'main'

jobs:
  ci_job:
    name: CI Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Python 3.11
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'
          
      - name: Install Dependencies + pytest-html
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-pyspark.txt

      - name: Run Pytest and Generate HTML Reports
        run: |
          pytest \
            --disable-warnings \
            --cov=./src \
            --cov-report=html

      - name: Upload Coverage HTML Report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: coverage-html
          path: htmlcov
